---
:ems:
  :ems_nuage:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:http_proxy:
  :nuage:
    :host:
    :password:
    :port:
    :user:
:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_nuage_network:
        :poll: 1.seconds
